DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output'          # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : GFBN                                            # name of the model you are using
  BACKBONE      : GFBN-B2                                         # model variant
  PRETRAINED    : 'checkpoints/pretrained/segformer/mit_b2.pth'     # backbone model's weight
  RESUME        : ''                                                # checkpoint file
  BOUNDARY      : 0

DATASET:
  NAME          : IRSEG                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'data/ir_seg_dataset-20230411T072452Z-001/ir_seg_dataset'                            # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['img']
  MODALS        : ['img', 'thermal']

TRAIN:
  IMAGE_SIZE    : [480, 640]      # training image size in (h, w)
  BATCH_SIZE    : 2               # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_START    : 300             # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : true            # use DDP training

LOSS:
  NAME          : CrossEntropy     # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio



EVAL:
  MODEL_PATH    : 'output/IRSEG_GFBN-B2_it/GFBN_GFBN-B2_IRSEG_epoch380_65.46.pth'
  IMAGE_SIZE    : [480, 640]      # evaluation image size in (h, w)
  BATCH_SIZE    : 1               # batch size used to train
  MSF:
    ENABLE      : false                                   # multi-scale and flip evaluation
    FLIP        : true                                    # use flip in evaluation
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation

TEST:
  MODEL_PATH    : 'output/IRSEG_GFBN-B2_it/GFBN_GFBN-B2_IRSEG_epoch380_65.46.pth'   # trained model file path
  FILE          : 'data/ir_seg_dataset-20230411T072452Z-001/ir_seg_dataset'                          # filename or foldername
  IMAGE_SIZE    : [480, 640]                            # inference image size in (h, w)
  OVERLAY       : false                                   # save the overlay result (image_alpha+label_alpha)
